### ISSUE TITLE
when I updated vue version to 2.7.0 why show this is error? how can i solve it 

### ISSUE THREAD

**Issue by jetBn** [vuejs/vue-class-component#620]
Type '{ slot: string; class: string; }' is not assignable to type 'ElementAttrs<HTMLAttributes>'.
  Property 'slot' does not exist on type 'ElementAttrs<HTMLAttributes>'.

**Comment by jetBn** [comment]
> Same here, it seems it's breaking a lot of packages using this library for their components. https://www.syncfusion.com/forums/176017/vue2-compatibility

when i update to 2.7.3, it's running is correct.

**Comment by dennybiasiolli** [comment]
> when i update to 2.7.3, it's running is correct.

It's running correctly, but it doesn't display components.
Do you see the Syncfusion button on the homepage? Or there is an error in the console?

**Comment by jetBn** [comment]
> > when i update to 2.7.3, it's running is correct.
> 
> It's running correctly, but it doesn't display components. Do you see the Syncfusion button on the homepage? Or there is an error in the console?

I not used @syncfusion/ej2-vue-buttons ui.
